import { useEffect, useState } from 'react'
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import { getToken } from './services/api'
import { getMe, getProjects } from './services/platform'
import type { Project, User } from './types'
import { Layout } from './components/layout'
import { DashboardPage, LoginPage, TaskDetailPage, TasksPage, WorkersPage, WorkflowRunPage, WorkflowsPage } from './pages'
function App() { const [token, setAuth] = useState(getToken()); const [projects, setProjects] = useState<Project[]>([]); const [user, setUser] = useState<User>(); const [projectId, setProjectId] = useState(sessionStorage.getItem('dtp.project') || ''); useEffect(() => { if (!token) return; void Promise.all([getProjects(), getMe()]).then(([{ items }, currentUser]) => { setProjects(items); setUser(currentUser); setProjectId(previous => previous || items[0]?.id || '') }).catch(() => setAuth(null)) }, [token]); useEffect(() => { if (projectId) sessionStorage.setItem('dtp.project', projectId) }, [projectId]); useEffect(() => { const expired = () => setAuth(null); window.addEventListener('auth-expired', expired); return () => window.removeEventListener('auth-expired', expired) }, []); const onLogin = () => { setAuth(getToken()); } ; if (!token) return <Routes><Route path="*" element={<LoginPage onLogin={onLogin}/>}/></Routes>; const page = projectId ? <Route element={<Layout user={user || { id: '', email: 'Authenticated user', role: '', created_at: '' }} projects={projects} selectedProject={projectId} onProject={setProjectId}/>}> <Route path="/" element={<DashboardPage projectId={projectId}/>}/><Route path="/tasks" element={<TasksPage projectId={projectId}/>}/><Route path="/tasks/:taskId" element={<TaskDetailPage/>}/><Route path="/workers" element={<WorkersPage/>}/><Route path="/workflows" element={<WorkflowsPage projectId={projectId}/>}/><Route path="/workflows/:workflowId/runs/:runId" element={<WorkflowRunPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route> : <Route path="*" element={<div className="p-8">Loading accessible projects…</div>}/>; return <Routes>{page}</Routes> }
export default function Root() { return <BrowserRouter><App/></BrowserRouter> }
